<?php


namespace app\components;


use app\models\Category;
use yii\base\Widget;

class MenuWidget extends Widget
{

    public $tpl;      //файл шаблона для CMS
    public $ul_class; //присваивание css класса для меню
    public $data;     //получаем массив категорий
    public $tree;     //передаем массив категорий в дерево
    public $menuHtml;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ($this->ul_class === null)
        {
            $this->ul_class = 'menu';
        }
        if ($this->tpl === null)
        {
            $this->tpl = 'menu';
        }

        $this->tpl .= '.php';

    }

    public function run()
    {

        //get cache
        $menu = \Yii::$app->cache->get('menu');
        if($menu){
            return $menu;
        }

        $this->data = Category::find()->select('id, parent_id, title')->indexBy('id')->asArray()->all();
        $this->tree = $this->getTree();
        $this->menuHtml = '<ul class="' . $this->ul_class . '">';
        $this->menuHtml .= $this->getMenuHtml($this->tree);
        $this->menuHtml .= '</ul>';

        // set cache
        $menu = \Yii::$app->cache->set('menu',$this->menuHtml, 60); // key - menu, our data - $this->menuHtml, duration - 60
        return $this->menuHtml;
    }

    protected function getTree(){
        $tree = [];
        foreach ($this->data as $id=> &$node)
        {
            if (!$node['parent_id'])
                $tree[$id] = &$node;
            else
                $this->data[$node['parent_id']]['children'][$node['id']] = &$node;
        }
        return $tree;
    }

    protected function getMenuHtml($tree){
        $str = '';
        foreach ($tree as $category){
            $str .= $this->catToTemplate($category);
        }
        return $str;
    }

    /*передача узлов дерева*/
    protected function catToTemplate($category){
        ob_start(); //буферизация вывода
        include __DIR__ . '/menu_tpl/' . $this->tpl;
        return ob_get_clean();
    }
}